-- ScriptCreator MySQL schema

CREATE TABLE IF NOT EXISTS scriptcreator_admins (
    identifier VARCHAR(100) PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scriptcreator_npcs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    model VARCHAR(64) NOT NULL,
    x DOUBLE NOT NULL,
    y DOUBLE NOT NULL,
    z DOUBLE NOT NULL,
    heading DOUBLE NOT NULL,
    scenario VARCHAR(128) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scriptcreator_blips (
    id INT AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(64) NOT NULL,
    sprite INT NOT NULL,
    color INT NOT NULL,
    scale DOUBLE NOT NULL,
    x DOUBLE NOT NULL,
    y DOUBLE NOT NULL,
    z DOUBLE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scriptcreator_markers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    markerType INT NOT NULL,
    r INT NOT NULL,
    g INT NOT NULL,
    b INT NOT NULL,
    a INT NOT NULL,
    x DOUBLE NOT NULL,
    y DOUBLE NOT NULL,
    z DOUBLE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scriptcreator_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    label VARCHAR(128) NOT NULL,
    weight DOUBLE NOT NULL DEFAULT 0.0,
    stackable TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scriptcreator_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url TEXT NOT NULL,
    label VARCHAR(128) DEFAULT NULL,
    x DOUBLE DEFAULT 0.0,
    y DOUBLE DEFAULT 0.0,
    z DOUBLE DEFAULT 0.0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scriptcreator_audit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    action VARCHAR(128) NOT NULL,
    actor VARCHAR(64) NOT NULL,
    target VARCHAR(128) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
